name: 'netease-recent-actions'
description: 'This action allows you to generate an svg profile from your NetEase Cloud Music account'
author: 'zonemeen <miqilin18@gmail.com>'

branding:
  icon: 'music'
  color: 'blue'

inputs:
  id:
    description: 'This is your NetEase Cloud Music account id.'
    required: true
  type:
    description: 'Song ranking type, 1 for weekData, 0 for allData'
    default: '1'
  number:
    description: 'The number of songs'
    default: '5'
  title:
    description: 'Title of svg profile'
    default: 'Recently Played'
  size:
    description: 'Size of the song picture'
    default: '800'
  width:
    description: 'Width of the card'
    default: '280'
  theme:
    description: 'Theme of the card'
    default: 'dark'
  column:
    description: 'Number of columns of the card'
    default: '1'
  show_percent:
    description: 'Whether to show the percentage of play count'
    default: '0'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        npm i -g pnpm
        pnpm install --no-frozen-lockfile
        node index.js --id ${{ inputs.id }} --type ${{ inputs.type }} --number ${{ inputs.number }} --title ${{ inputs.title }} --size ${{ inputs.size }} --width ${{ inputs.width }} --theme ${{ inputs.theme }} --column ${{ inputs.column }} --show_percent ${{ inputs.show_percent }}
        cp 163.svg ${{ github.workspace }}
        cd ${{ github.workspace }}
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git pull
        git add .
        git commit -m "Update 163.svg"
        git push

outputs:
  deployment-status:
    description: 'The status of the deployment that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'
